/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import java.time.LocalDate;
import java.time.LocalDateTime;

import nl.tudelft.simulation.housinggame.data.tables.Gamesession;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesessionRecord extends UpdatableRecordImpl<GamesessionRecord> implements Record7<UInteger, String, String, String, LocalDateTime, LocalDate, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.gamesession.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.gamesession.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>housinggame.gamesession.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>housinggame.gamesession.location</code>.
     */
    public void setLocation(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.location</code>.
     */
    public String getLocation() {
        return (String) get(3);
    }

    /**
     * Setter for <code>housinggame.gamesession.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>housinggame.gamesession.date</code>.
     */
    public void setDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(5);
    }

    /**
     * Setter for <code>housinggame.gamesession.gameversion_id</code>.
     */
    public void setGameversionId(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>housinggame.gamesession.gameversion_id</code>.
     */
    public UInteger getGameversionId() {
        return (UInteger) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UInteger, String, String, String, LocalDateTime, LocalDate, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UInteger, String, String, String, LocalDateTime, LocalDate, UInteger> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Gamesession.GAMESESSION.ID;
    }

    @Override
    public Field<String> field2() {
        return Gamesession.GAMESESSION.NAME;
    }

    @Override
    public Field<String> field3() {
        return Gamesession.GAMESESSION.PASSWORD;
    }

    @Override
    public Field<String> field4() {
        return Gamesession.GAMESESSION.LOCATION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Gamesession.GAMESESSION.CREATE_TIME;
    }

    @Override
    public Field<LocalDate> field6() {
        return Gamesession.GAMESESSION.DATE;
    }

    @Override
    public Field<UInteger> field7() {
        return Gamesession.GAMESESSION.GAMEVERSION_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public String component4() {
        return getLocation();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDate component6() {
        return getDate();
    }

    @Override
    public UInteger component7() {
        return getGameversionId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public String value4() {
        return getLocation();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDate value6() {
        return getDate();
    }

    @Override
    public UInteger value7() {
        return getGameversionId();
    }

    @Override
    public GamesessionRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public GamesessionRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GamesessionRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public GamesessionRecord value4(String value) {
        setLocation(value);
        return this;
    }

    @Override
    public GamesessionRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public GamesessionRecord value6(LocalDate value) {
        setDate(value);
        return this;
    }

    @Override
    public GamesessionRecord value7(UInteger value) {
        setGameversionId(value);
        return this;
    }

    @Override
    public GamesessionRecord values(UInteger value1, String value2, String value3, String value4, LocalDateTime value5, LocalDate value6, UInteger value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamesessionRecord
     */
    public GamesessionRecord() {
        super(Gamesession.GAMESESSION);
    }

    /**
     * Create a detached, initialised GamesessionRecord
     */
    public GamesessionRecord(UInteger id, String name, String password, String location, LocalDateTime createTime, LocalDate date, UInteger gameversionId) {
        super(Gamesession.GAMESESSION);

        setId(id);
        setName(name);
        setPassword(password);
        setLocation(location);
        setCreateTime(createTime);
        setDate(date);
        setGameversionId(gameversionId);
        resetChangedOnNotNull();
    }
}
