/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Gameversion;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameversionRecord extends UpdatableRecordImpl<GameversionRecord> implements Record2<UInteger, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.gameversion.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.gameversion.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.gameversion.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.gameversion.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Gameversion.GAMEVERSION.ID;
    }

    @Override
    public Field<String> field2() {
        return Gameversion.GAMEVERSION.NAME;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public GameversionRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public GameversionRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GameversionRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameversionRecord
     */
    public GameversionRecord() {
        super(Gameversion.GAMEVERSION);
    }

    /**
     * Create a detached, initialised GameversionRecord
     */
    public GameversionRecord(UInteger id, String name) {
        super(Gameversion.GAMEVERSION);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
