/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables.records;


import nl.tudelft.simulation.housinggame.data.tables.Newsparameters;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NewsparametersRecord extends UpdatableRecordImpl<NewsparametersRecord> implements Record13<UInteger, Byte, Byte, UInteger, UInteger, UInteger, Integer, Integer, Double, Integer, Integer, UInteger, UInteger> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>housinggame.newsparameters.id</code>.
     */
    public void setId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.id</code>.
     */
    public UInteger getId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>housinggame.newsparameters.house_discount_euros</code>.
     */
    public void setHouseDiscountEuros(Byte value) {
        set(1, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.house_discount_euros</code>.
     */
    public Byte getHouseDiscountEuros() {
        return (Byte) get(1);
    }

    /**
     * Setter for
     * <code>housinggame.newsparameters.house_discount_percent</code>.
     */
    public void setHouseDiscountPercent(Byte value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>housinggame.newsparameters.house_discount_percent</code>.
     */
    public Byte getHouseDiscountPercent() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>housinggame.newsparameters.house_discount_year1</code>.
     * House discount year 1 after flooding, in Euros or as a percentage
     */
    public void setHouseDiscountYear1(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.house_discount_year1</code>.
     * House discount year 1 after flooding, in Euros or as a percentage
     */
    public UInteger getHouseDiscountYear1() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>housinggame.newsparameters.house_discount_year2</code>.
     * House discount year 2 after flooding, in Euros or as a percentage
     */
    public void setHouseDiscountYear2(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.house_discount_year2</code>.
     * House discount year 2 after flooding, in Euros or as a percentage
     */
    public UInteger getHouseDiscountYear2() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>housinggame.newsparameters.house_discount_year3</code>.
     * House discount year 3 after flooding, in Euros or as a percentage
     */
    public void setHouseDiscountYear3(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.house_discount_year3</code>.
     * House discount year 3 after flooding, in Euros or as a percentage
     */
    public UInteger getHouseDiscountYear3() {
        return (UInteger) get(5);
    }

    /**
     * Setter for
     * <code>housinggame.newsparameters.pluvial_protection_change</code>.
     */
    public void setPluvialProtectionChange(Integer value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>housinggame.newsparameters.pluvial_protection_change</code>.
     */
    public Integer getPluvialProtectionChange() {
        return (Integer) get(6);
    }

    /**
     * Setter for
     * <code>housinggame.newsparameters.fluvial_protection_change</code>.
     */
    public void setFluvialProtectionChange(Integer value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>housinggame.newsparameters.fluvial_protection_change</code>.
     */
    public Integer getFluvialProtectionChange() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>housinggame.newsparameters.tax_change</code>.
     */
    public void setTaxChange(Double value) {
        set(8, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.tax_change</code>.
     */
    public Double getTaxChange() {
        return (Double) get(8);
    }

    /**
     * Setter for
     * <code>housinggame.newsparameters.satisfaction_living_bonus</code>.
     */
    public void setSatisfactionLivingBonus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>housinggame.newsparameters.satisfaction_living_bonus</code>.
     */
    public Integer getSatisfactionLivingBonus() {
        return (Integer) get(9);
    }

    /**
     * Setter for
     * <code>housinggame.newsparameters.satisfaction_move_change</code>.
     */
    public void setSatisfactionMoveChange(Integer value) {
        set(10, value);
    }

    /**
     * Getter for
     * <code>housinggame.newsparameters.satisfaction_move_change</code>.
     */
    public Integer getSatisfactionMoveChange() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>housinggame.newsparameters.newsitem_id</code>.
     */
    public void setNewsitemId(UInteger value) {
        set(11, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.newsitem_id</code>.
     */
    public UInteger getNewsitemId() {
        return (UInteger) get(11);
    }

    /**
     * Setter for <code>housinggame.newsparameters.community_id</code>. When
     * community_id is NOT filled, all communities are affected equally.
     */
    public void setCommunityId(UInteger value) {
        set(12, value);
    }

    /**
     * Getter for <code>housinggame.newsparameters.community_id</code>. When
     * community_id is NOT filled, all communities are affected equally.
     */
    public UInteger getCommunityId() {
        return (UInteger) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<UInteger, Byte, Byte, UInteger, UInteger, UInteger, Integer, Integer, Double, Integer, Integer, UInteger, UInteger> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<UInteger, Byte, Byte, UInteger, UInteger, UInteger, Integer, Integer, Double, Integer, Integer, UInteger, UInteger> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<UInteger> field1() {
        return Newsparameters.NEWSPARAMETERS.ID;
    }

    @Override
    public Field<Byte> field2() {
        return Newsparameters.NEWSPARAMETERS.HOUSE_DISCOUNT_EUROS;
    }

    @Override
    public Field<Byte> field3() {
        return Newsparameters.NEWSPARAMETERS.HOUSE_DISCOUNT_PERCENT;
    }

    @Override
    public Field<UInteger> field4() {
        return Newsparameters.NEWSPARAMETERS.HOUSE_DISCOUNT_YEAR1;
    }

    @Override
    public Field<UInteger> field5() {
        return Newsparameters.NEWSPARAMETERS.HOUSE_DISCOUNT_YEAR2;
    }

    @Override
    public Field<UInteger> field6() {
        return Newsparameters.NEWSPARAMETERS.HOUSE_DISCOUNT_YEAR3;
    }

    @Override
    public Field<Integer> field7() {
        return Newsparameters.NEWSPARAMETERS.PLUVIAL_PROTECTION_CHANGE;
    }

    @Override
    public Field<Integer> field8() {
        return Newsparameters.NEWSPARAMETERS.FLUVIAL_PROTECTION_CHANGE;
    }

    @Override
    public Field<Double> field9() {
        return Newsparameters.NEWSPARAMETERS.TAX_CHANGE;
    }

    @Override
    public Field<Integer> field10() {
        return Newsparameters.NEWSPARAMETERS.SATISFACTION_LIVING_BONUS;
    }

    @Override
    public Field<Integer> field11() {
        return Newsparameters.NEWSPARAMETERS.SATISFACTION_MOVE_CHANGE;
    }

    @Override
    public Field<UInteger> field12() {
        return Newsparameters.NEWSPARAMETERS.NEWSITEM_ID;
    }

    @Override
    public Field<UInteger> field13() {
        return Newsparameters.NEWSPARAMETERS.COMMUNITY_ID;
    }

    @Override
    public UInteger component1() {
        return getId();
    }

    @Override
    public Byte component2() {
        return getHouseDiscountEuros();
    }

    @Override
    public Byte component3() {
        return getHouseDiscountPercent();
    }

    @Override
    public UInteger component4() {
        return getHouseDiscountYear1();
    }

    @Override
    public UInteger component5() {
        return getHouseDiscountYear2();
    }

    @Override
    public UInteger component6() {
        return getHouseDiscountYear3();
    }

    @Override
    public Integer component7() {
        return getPluvialProtectionChange();
    }

    @Override
    public Integer component8() {
        return getFluvialProtectionChange();
    }

    @Override
    public Double component9() {
        return getTaxChange();
    }

    @Override
    public Integer component10() {
        return getSatisfactionLivingBonus();
    }

    @Override
    public Integer component11() {
        return getSatisfactionMoveChange();
    }

    @Override
    public UInteger component12() {
        return getNewsitemId();
    }

    @Override
    public UInteger component13() {
        return getCommunityId();
    }

    @Override
    public UInteger value1() {
        return getId();
    }

    @Override
    public Byte value2() {
        return getHouseDiscountEuros();
    }

    @Override
    public Byte value3() {
        return getHouseDiscountPercent();
    }

    @Override
    public UInteger value4() {
        return getHouseDiscountYear1();
    }

    @Override
    public UInteger value5() {
        return getHouseDiscountYear2();
    }

    @Override
    public UInteger value6() {
        return getHouseDiscountYear3();
    }

    @Override
    public Integer value7() {
        return getPluvialProtectionChange();
    }

    @Override
    public Integer value8() {
        return getFluvialProtectionChange();
    }

    @Override
    public Double value9() {
        return getTaxChange();
    }

    @Override
    public Integer value10() {
        return getSatisfactionLivingBonus();
    }

    @Override
    public Integer value11() {
        return getSatisfactionMoveChange();
    }

    @Override
    public UInteger value12() {
        return getNewsitemId();
    }

    @Override
    public UInteger value13() {
        return getCommunityId();
    }

    @Override
    public NewsparametersRecord value1(UInteger value) {
        setId(value);
        return this;
    }

    @Override
    public NewsparametersRecord value2(Byte value) {
        setHouseDiscountEuros(value);
        return this;
    }

    @Override
    public NewsparametersRecord value3(Byte value) {
        setHouseDiscountPercent(value);
        return this;
    }

    @Override
    public NewsparametersRecord value4(UInteger value) {
        setHouseDiscountYear1(value);
        return this;
    }

    @Override
    public NewsparametersRecord value5(UInteger value) {
        setHouseDiscountYear2(value);
        return this;
    }

    @Override
    public NewsparametersRecord value6(UInteger value) {
        setHouseDiscountYear3(value);
        return this;
    }

    @Override
    public NewsparametersRecord value7(Integer value) {
        setPluvialProtectionChange(value);
        return this;
    }

    @Override
    public NewsparametersRecord value8(Integer value) {
        setFluvialProtectionChange(value);
        return this;
    }

    @Override
    public NewsparametersRecord value9(Double value) {
        setTaxChange(value);
        return this;
    }

    @Override
    public NewsparametersRecord value10(Integer value) {
        setSatisfactionLivingBonus(value);
        return this;
    }

    @Override
    public NewsparametersRecord value11(Integer value) {
        setSatisfactionMoveChange(value);
        return this;
    }

    @Override
    public NewsparametersRecord value12(UInteger value) {
        setNewsitemId(value);
        return this;
    }

    @Override
    public NewsparametersRecord value13(UInteger value) {
        setCommunityId(value);
        return this;
    }

    @Override
    public NewsparametersRecord values(UInteger value1, Byte value2, Byte value3, UInteger value4, UInteger value5, UInteger value6, Integer value7, Integer value8, Double value9, Integer value10, Integer value11, UInteger value12, UInteger value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NewsparametersRecord
     */
    public NewsparametersRecord() {
        super(Newsparameters.NEWSPARAMETERS);
    }

    /**
     * Create a detached, initialised NewsparametersRecord
     */
    public NewsparametersRecord(UInteger id, Byte houseDiscountEuros, Byte houseDiscountPercent, UInteger houseDiscountYear1, UInteger houseDiscountYear2, UInteger houseDiscountYear3, Integer pluvialProtectionChange, Integer fluvialProtectionChange, Double taxChange, Integer satisfactionLivingBonus, Integer satisfactionMoveChange, UInteger newsitemId, UInteger communityId) {
        super(Newsparameters.NEWSPARAMETERS);

        setId(id);
        setHouseDiscountEuros(houseDiscountEuros);
        setHouseDiscountPercent(houseDiscountPercent);
        setHouseDiscountYear1(houseDiscountYear1);
        setHouseDiscountYear2(houseDiscountYear2);
        setHouseDiscountYear3(houseDiscountYear3);
        setPluvialProtectionChange(pluvialProtectionChange);
        setFluvialProtectionChange(fluvialProtectionChange);
        setTaxChange(taxChange);
        setSatisfactionLivingBonus(satisfactionLivingBonus);
        setSatisfactionMoveChange(satisfactionMoveChange);
        setNewsitemId(newsitemId);
        setCommunityId(communityId);
        resetChangedOnNotNull();
    }
}
