/*
 * This file is generated by jOOQ.
 */
package nl.tudelft.simulation.housinggame.data.tables;


import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import nl.tudelft.simulation.housinggame.data.Housinggame;
import nl.tudelft.simulation.housinggame.data.Keys;
import nl.tudelft.simulation.housinggame.data.tables.records.DamageRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function3;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Damage extends TableImpl<DamageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>housinggame.damage</code>
     */
    public static final Damage DAMAGE = new Damage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DamageRecord> getRecordType() {
        return DamageRecord.class;
    }

    /**
     * The column <code>housinggame.damage.id</code>.
     */
    public final TableField<DamageRecord, UInteger> ID = createField(DSL.name("id"), SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>housinggame.damage.name</code>.
     */
    public final TableField<DamageRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>housinggame.damage.description</code>.
     */
    public final TableField<DamageRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private Damage(Name alias, Table<DamageRecord> aliased) {
        this(alias, aliased, null);
    }

    private Damage(Name alias, Table<DamageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>housinggame.damage</code> table reference
     */
    public Damage(String alias) {
        this(DSL.name(alias), DAMAGE);
    }

    /**
     * Create an aliased <code>housinggame.damage</code> table reference
     */
    public Damage(Name alias) {
        this(alias, DAMAGE);
    }

    /**
     * Create a <code>housinggame.damage</code> table reference
     */
    public Damage() {
        this(DSL.name("damage"), null);
    }

    public <O extends Record> Damage(Table<O> child, ForeignKey<O, DamageRecord> key) {
        super(child, key, DAMAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Housinggame.HOUSINGGAME;
    }

    @Override
    public Identity<DamageRecord, UInteger> getIdentity() {
        return (Identity<DamageRecord, UInteger>) super.getIdentity();
    }

    @Override
    public UniqueKey<DamageRecord> getPrimaryKey() {
        return Keys.KEY_DAMAGE_PRIMARY;
    }

    @Override
    public List<UniqueKey<DamageRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.KEY_DAMAGE_ID_UNIQUE);
    }

    @Override
    public Damage as(String alias) {
        return new Damage(DSL.name(alias), this);
    }

    @Override
    public Damage as(Name alias) {
        return new Damage(alias, this);
    }

    @Override
    public Damage as(Table<?> alias) {
        return new Damage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Damage rename(String name) {
        return new Damage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Damage rename(Name name) {
        return new Damage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Damage rename(Table<?> name) {
        return new Damage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row3 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row3<UInteger, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function3<? super UInteger, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function3<? super UInteger, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
